# phantom - docker-composer.yml of postgresql + redis + pgadmin, for sample only.
# (c) 2023 SuperSonic (https://github.com/supersonictw)

version: "3.5"
services:
  database:
    image: postgres:12-alpine
    container_name: phantom-data
    ports:
      - 127.0.0.1:2101:5432
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - phantom
    environment:
      POSTGRES_PASSWORD: phantom-admin
    restart: always

  cache:
    image: redis:7.0
    container_name: phantom-cache
    ports:
      - 127.0.0.1:2102:6379
    networks:
      - phantom
    restart: always

  pgadmin:
    image: dpage/pgadmin4:6.15
    container_name: phantom-pga
    ports:
      - 127.0.0.1:2103:80
    networks:
      - phantom
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@example.org"
      PGADMIN_DEFAULT_PASSWORD: "phantom-admin"
      PGADMIN_CONFIG_SESSION_EXPIRATION_TIME: 365
      PGADMIN_CONFIG_MAX_SESSION_IDLE_TIME: 60
    restart: always

volumes:
  database:
    driver: local

networks:
  phantom:
    name: phantom
    driver: bridge
